#!/bin/sh
HERE=$(dirname "$0")
$HERE/import-feeds.py
$HERE/render.py $HERE/templates/config.ini > /pamelaselle.com/ironbloggista/tools/config.ini
$HERE/update-participants.py
cp "$HERE/bloggers.yml" /pamelaselle.com/ironbloggista/tools